### ISSUE TITLE
selenium failing with `selenium.common.exceptions.TimeoutException`

### ISSUE THREAD

**Issue by matthewfeickert** [pyhf/public-probability-models#29]
For the last 3 weeks [`atlas/main.py`](https://github.com/pyhf/public-probability-models/blob/a358a8172abd6777d6ecc810d00f1f0830d3f8ff/atlas/main.py)

https://github.com/pyhf/public-probability-models/blob/a358a8172abd6777d6ecc810d00f1f0830d3f8ff/atlas/main.py#L27-L32

has been failing with a `selenium.common.exceptions.TimeoutException`

```pytb
[WDM] - Downloading:   0%|          | 0.00/7.06M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 7.06M/7.06M [00:00<00:00, 138MB/s]
Traceback (most recent call last):
  File "/__w/public-probability-models/public-probability-models/atlas/main.py", line 28, in <module>
    WebDriverWait(driver, timeout=60).until(
  File "/__w/public-probability-models/public-probability-models/venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5603ccc314e3 <unknown>
#1 0x5603cc960c76 <unknown>
#2 0x5603cc99cc96 <unknown>
#3 0x5603cc99cdc1 <unknown>
#4 0x5603cc9d67f4 <unknown>
#5 0x5603cc9bc03d <unknown>
#6 0x5603cc9d430e <unknown>
#7 0x5603cc9bbde3 <unknown>
#8 0x5603cc9912dd <unknown>
#9 0x5603cc99234e <unknown>
#10 0x5603ccbf13e4 <unknown>
#11 0x5603ccbf53d7 <unknown>
#12 0x5603ccbffb20 <unknown>
#13 0x5603ccbf6023 <unknown>
#14 0x5603ccbc41aa <unknown>
#15 0x5603ccc1a6b8 <unknown>
#16 0x5603ccc1a847 <unknown>
#17 0x5603ccc2a243 <unknown>
#18 0x7f939951fea7 start_thread
```

We should fix this to get things online again.

**Comment by kratsg** [comment]
Cannot reproduce on Mac. Must be a webdriver update in GitHub Action runners.
