### ISSUE TITLE
selenium failing to create ChromeDriver

### ISSUE THREAD

**Issue by matthewfeickert** [pyhf/public-probability-models#6]
I haven't looked at this yet, but

https://github.com/pyhf/public-probability-models/blob/43c141b0e0a894917584d80c1bceaf9cf019652a/atlas/main.py#L24

is failing with

```pytb
Traceback (most recent call last):
  File "/home/runner/work/public-probability-models/public-probability-models/atlas/main.py", line 24, in <module>
    with webdriver.Chrome(options=options, service=service) as driver:
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line [24](https://github.com/pyhf/public-probability-models/runs/8196748811?check_suite_focus=true#step:6:25)3, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 105
Current browser version is 104.0.5112.0 with binary path /usr/bin/chromium
```

I'm not sure if we need to constrain the version of chromium or use a lock file to constrain the versions of the dependencies of

https://github.com/pyhf/public-probability-models/blob/43c141b0e0a894917584d80c1bceaf9cf019652a/atlas/requirements.txt#L1-L2

better.

**Comment by kratsg** [comment]
We need to really remove `chrome` from the images.

**Comment by matthewfeickert** [comment]
> We need to really remove `chrome` from the images.

As purge isn't doing it, do we need to run everything in a Docker container that gets built at runtime?

**Comment by kratsg** [comment]
No. We need to just remove the binary from the path. That's all. Just manually rm it.
